// Explicit typed instruction content for every mode-specific stage, keyed by
// exact stage ID so that stages sharing a name across modes (e.g. every
// mode's "implementation" stage) are never accidentally conflated.
//
// stage.feature.implementation is hand-curated (Batch 2 representative
// integration). Every other entry was mechanically extracted from the
// pristine v1.2.0 src/promptGenerator.ts (commit 983a476, via `git show
// HEAD:src/promptGenerator.ts`) by rendering every stage prompt with a fixed
// synthetic RunMetadata and splitting each prompt's Task:/Stop conditions:
// section into prose (taskInstructions), bullet items (validationRequirements),
// and stop-condition bullets (stopConditions) -- excluding lines that carry
// only dynamic run-specific values (paths, run IDs), which remain
// prompt-owned in promptGenerator.ts. This is a deterministic derivation from
// the authoritative v1.2.0 prompt text, not fabricated content.

export interface StageInstructionContent {
  taskInstructions: string;
  validationRequirements: string[];
  stopConditions: string[];
}

export const EMPTY_STAGE_INSTRUCTION_CONTENT: StageInstructionContent = {
  taskInstructions: '',
  validationRequirements: [],
  stopConditions: [],
};

export const STAGE_INSTRUCTION_CONTENT: Record<string, StageInstructionContent> = {
  'stage.feature.implementation': {
    taskInstructions:
      'Implement the PseudocodePacket in the current project and produce the required ImplementationReport artifact.\n\n' +
      'Read required source files and implement from the PseudocodePacket.\n' +
      'Follow the architecture and patterns identified in the ArchitectureContextPacket.\n' +
      'Preserve the BehaviorModel.',
    validationRequirements: [
      'The ImplementationReport must record files read.',
      'The ImplementationReport must record files changed.',
      'The ImplementationReport must record behavior implemented.',
      'The ImplementationReport must record pseudocode sections implemented.',
      'The ImplementationReport must record assumptions preserved.',
      'The ImplementationReport must record assumptions removed or guarded.',
      'The ImplementationReport must record deviations from the PseudocodePacket and the reason for each deviation.',
      'The ImplementationReport must record blockers encountered.',
      'The ImplementationReport must record unresolved risks.',
      'The ImplementationReport must record tests that should be run.',
      'The ImplementationReport must record notes for the test implementation stage.',
    ],
    stopConditions: [
      'do not broaden scope without reporting a blocker',
      'do not create parallel architecture',
      'do not claim verification success without command evidence',
      'do not ignore contradictions in prior artifacts',
      'do not modify files outside justified scope',
      'do not perform test-implementation-stage work in this stage',
    ],
  },
  "stage.extraction.behavior-model": {
    taskInstructions: "Use the GoldenBehaviorContract as the primary source of truth for the target behavior.\nMap behavior to the target system, not to the source architecture.\nExtraction guardrails:\nThe BehaviorModel must define:",
    validationRequirements: [
      "Do not use source implementation details as the behavior definition.",
      "Do not port behavior not listed in the SourceToTargetPortingMap or GoldenBehaviorContract.",
      "do not start implementing in this stage.",
      "Do not write test files.",
      "behavior summary (target system only)",
      "externally visible behavior",
      "internal supporting behavior",
      "state variables",
      "inputs",
      "events",
      "derived values",
      "invariants",
      "valid states",
      "invalid states",
      "boundaries and partitions",
      "empty states",
      "error states",
      "loading or pending states when relevant",
      "external contracts",
      "state transitions",
      "behavior from the GoldenBehaviorContract to preserve",
      "behavior intentionally changed from source",
      "unresolved design questions",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not produce source architecture in behavior descriptions",
    ],
  },
  "stage.extraction.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "Mode: extraction",
      "Run ID",
      "Original extraction request",
      "Source repository",
      "Target repository",
      "Final status (judge verdict)",
      "Source workflow map",
      "Source-to-target porting map",
      "Do-not-port list",
      "Golden behavior contract",
      "Target architecture proposal",
      "Source components reused",
      "Source components rewritten",
      "Source components discarded",
      "Files changed in target repository",
      "Files changed in source repository (normally: none)",
      "Tests added or updated",
      "Verification commands and results",
      "Judge result",
      "Remaining risks",
      "Recommended next extraction or implementation step",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not hide unresolved risks",
    ],
  },
  "stage.extraction.golden-behavior-contract": {
    taskInstructions: "Define the exact behavior that the target implementation must satisfy.\nThis is the primary source of truth for the target implementation and the judge stage.\nNo production implementation should begin before this artifact exists.\nExtraction guardrails:\nRequired sections:\nFor fragile or complex workflows, define specific testable statements. Examples:\nCompletion criteria:",
    validationRequirements: [
      "Do not include source implementation details as requirements.",
      "Do not include source file paths or source architecture references as requirements.",
      "Do not reference source architecture as the target design.",
      "do not start implementing in this stage.",
      "Do not modify source or target repositories in this stage.",
      "The source repository is evidence. This artifact defines what must be true in the target, not what exists in the source.",
      "User-visible behavior",
      "API behavior",
      "State behavior",
      "Sorting and ranking behavior",
      "Pagination behavior",
      "Selection behavior",
      "Error and empty-state behavior",
      "Edge cases",
      "Non-negotiable regression tests",
      "Acceptance criteria",
      "Search results must be ordered by relevance descending.",
      "Page-size options must be 10, 30, 50, and 100.",
      "Pagination must use Previous, numbered pages, ellipsis, last page, and Next.",
      "Selection must be stored by stable item ID, not page index.",
      "Select all current page must select only visible page items.",
      "Deselect all current page must deselect only visible page items.",
      "Automatic mode must use top N valid ranked results, not the first N visible rows.",
      "Manual mode must use only user-selected items.",
      "Changing page size must preserve valid selections.",
      "Out-of-range pages must be clamped.",
      "Every user-visible behavior item is described precisely enough that a developer could implement it without reading the source repository.",
      "Every non-negotiable regression test is listed.",
    ],
    stopConditions: [
      "do not write pseudocode",
      "do not write test files",
      "do not implement code",
      "do not reference source architecture as the target design",
    ],
  },
  "stage.extraction.implementation": {
    taskInstructions:
      "Use the GoldenBehaviorContract as the implementation source of truth.\nFollow the TargetArchitectureProposal and PseudocodePacket.\nImplement in the target repository only. The source repository is read-only evidence.\nExtraction guardrails:\nThe ImplementationReport must include:",
    validationRequirements: [
      "Implement only in the target repository unless source repository changes are explicitly permitted by the request brief.",
      "Do not copy files directly from source to target.",
      "Do not port systems listed in the DoNotPortList.",
      "Do not import source repository modules into the target.",
      "Do not assume source architecture is the required target architecture.",
      "The GoldenBehaviorContract defines what must be true - not the source code.",
      "files read (source and target)",
      "files created or changed (target only)",
      "behavior implemented (must map to GoldenBehaviorContract items)",
      "pseudocode sections implemented",
      "porting decisions applied (from SourceToTargetPortingMap)",
      "systems excluded (from DoNotPortList)",
      "deviations from the PseudocodePacket and reason for each",
      "source repository changes made, if any (normally: none)",
      "blockers encountered",
      "unresolved risks",
      "tests that should be run",
      "notes for the test implementation stage",
    ],
    stopConditions: [
      "do not port DoNotPortList systems",
      "do not modify the source repository unless explicitly allowed by the request brief",
      "do not claim verification success without command evidence",
      "do not broaden scope without reporting a blocker",
    ],
  },
  "stage.extraction.judge": {
    taskInstructions: "Do not mark the run as passed unless the target implementation satisfies the GoldenBehaviorContract.\nThe JudgeReport must assess:\nVerdict must be one of:\nPASS | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | DO_NOT_PORT_VIOLATION |\nGOLDEN_CONTRACT_NOT_SATISFIED | NEED_VERIFICATION | SCOPE_VIOLATION | BLOCKED\nSource repository\nTarget repository",
    validationRequirements: [
      "implementation vs GoldenBehaviorContract (primary gate)",
      "implementation vs PseudocodePacket",
      "implementation vs TargetArchitectureProposal",
      "tests vs TestStrategyPacket",
      "tests vs GoldenBehaviorContract non-negotiable regression tests",
      "DoNotPortList compliance: no excluded systems were ported",
      "SourceToTargetPortingMap decisions followed",
      "source repository read-only compliance: was the source repository modified?",
      "behavior coverage",
      "verification evidence",
      "scope control",
      "risks and gaps",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide gaps in GoldenBehaviorContract coverage",
    ],
  },
  "stage.extraction.porting-map": {
    taskInstructions: "Classify each source subsystem as: port as-is, port with refactor, rewrite cleanly, discard, or postpone.\nExplicitly list every source system that must not be ported.\nExtraction guardrails:\nSourceToTargetPortingMap required structure for each item:\nDoNotPortList required sections:\nCompletion criteria:",
    validationRequirements: [
      "The source repository is evidence, not destiny. Do not port code just because it exists.",
      "Do not create a second copy of the old architecture inside the target project.",
      "Do not port authentication, persistence, workspaces, database schema, background jobs, or downstream workflows unless explicitly in scope.",
      "Do not preserve old UI labels if they conflict with the new workflow.",
      "do not start implementing in this stage.",
      "Do not modify source or target repositories.",
      "Source behavior",
      "Source files or symbols",
      "Target behavior",
      "Target module or component (planned target location)",
      "Decision: port as-is | port with refactor | rewrite cleanly | discard | postpone",
      "Reason",
      "Required tests",
      "Risks",
      "Systems excluded from the target project",
      "UI labels excluded from the target project",
      "Backend routes excluded from the target project",
      "Persistence layers excluded from the target project",
      "Downstream workflows excluded from the target project",
      "Reason each exclusion exists",
      "Consequences if accidentally ported",
      "Every significant source subsystem has a documented decision in SourceToTargetPortingMap",
      "Every discarded subsystem also appears in DoNotPortList",
      "Both artifact files must be present before the next stage can proceed",
    ],
    stopConditions: [
      "do not include implementation code",
      "do not start implementing",
      "do not write test files",
      "do not modify source or target repositories",
    ],
  },
  "stage.extraction.pseudocode-packet": {
    taskInstructions:
      "Convert the BehaviorModel into implementation-neutral pseudocode for the target system.\nThis is the shared design contract for both implementation and testing.\nMap to the target architecture, not to the source architecture.\nExtraction guardrails:\nThe PseudocodePacket must define:",
    validationRequirements: [
      "Do not copy source implementation code into this artifact.",
      "Do not reference source module paths as the target module paths.",
      "Do not port patterns from the DoNotPortList.",
      "do not start implementing in this stage.",
      "behavior references (from GoldenBehaviorContract)",
      "data flow",
      "state flow",
      "state transitions",
      "derived-value rules",
      "validation rules",
      "empty-state handling",
      "error-state handling",
      "external contract handling",
      "target component, module, service, route, command, or helper contracts",
      "acceptance criteria",
      "likely files or modules to create or modify in the target repository",
      "implementation constraints",
      "assumptions preserved",
      "unresolved implementation questions",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not modify source or target repositories",
    ],
  },
  "stage.extraction.request-brief": {
    taskInstructions: "Extraction guardrails:\nThe ExtractionRequestBrief must define:",
    validationRequirements: [
      "The source repository is evidence, not destiny. Do not port code just because it exists.",
      "Do not start by copying files from source to target.",
      "Do not assume the source architecture is the desired target architecture.",
      "Do not implement anything in the target repository in this stage.",
      "original request (verbatim from 00-request.txt)",
      "source repository",
      "target repository",
      "workflow or feature to extract",
      "desired target scope (what should exist in the target when complete)",
      "features explicitly excluded from the extraction",
      "critical behaviors to preserve from the source workflow",
      "expected deliverables",
      "constraints",
      "success criteria",
      "ambiguity or missing information",
      "expected next stage: source-architecture-context",
    ],
    stopConditions: [
      "do not inspect source code deeply in this stage",
      "do not write pseudocode",
      "do not write tests",
      "do not start implementing in this stage",
      "do not port files",
    ],
  },
  "stage.extraction.source-architecture-context": {
    taskInstructions: "Use my-dev-kit to inspect the source repository and produce a supporting retrieval report and source architecture context artifact.\n1. Supporting retrieval report\n2. Required workflow artifact\nExtraction guardrails:\nSource repository inspection sequence (when my-dev-kit is available):\nStep 1 - Index the source repository into its own index directory:\nStep 2 - Search for task-specific candidate nodes in the source repository:\nRun multiple queries for different aspects of the extraction request.\nStep 3 - Look up selected nodes and their relationships:\nStep 4 - Slice around the strongest relevant node:\nStep 5 - Retrieve exact symbol source (preferred):\nStep 6 - Use line-range retrieval only as fallback when symbol retrieval is insufficient:\nStep 7 - Avoid reading whole source files unless bounded retrieval is insufficient. If a whole file must be read, state why.\nIf my-dev-kit is unavailable, use focused manual inspection of relevant files and symbols in the source repository. Document what was inspected and why.\nThe SourceArchitectureContextPacket must identify relevant source architecture context without deciding what to port.",
    validationRequirements: [
      "The source repository is evidence, not destiny. Do not port code just because it exists.",
      "Do not start by reading whole source files.",
      "Do not use target repository indexing to infer source behavior.",
      "Do not modify the source repository.",
      "Do not decide porting strategy in this stage.",
      "Do not modify the target repository in this stage.",
      "Source and target index directories must stay separate.",
    ],
    stopConditions: [
      "do not decide porting strategy in this stage",
      "do not write pseudocode",
      "do not start implementing in this stage",
      "do not write test files",
      "do not modify source or target repositories",
    ],
  },
  "stage.extraction.source-workflow-map": {
    taskInstructions: "This stage describes what exists in the source repository. It does not decide what to port.\nExtraction guardrails:\nRequired sections for SourceWorkflowMap:",
    validationRequirements: [
      "The source repository is evidence, not destiny. Do not port code just because it exists.",
      "Do not decide porting strategy in this stage.",
      "Do not start by copying files.",
      "Do not modify the source repository.",
      "Do not modify the target repository in this stage.",
      "do not start implementing in this stage.",
      "Source repo path",
      "Workflow entry point",
      "User-facing steps",
      "Frontend components",
      "Frontend state owners",
      "API routes",
      "Backend services",
      "Data contracts",
      "Persistence dependencies",
      "External service dependencies",
      "Tests found",
      "Known behavior risks",
      "Ambiguous or missing context",
    ],
    stopConditions: [
      "do not include porting decisions",
      "do not include implementation plans",
      "do not include target architecture details",
      "do not write pseudocode",
      "do not implement code",
      "do not write test files",
      "completion criteria: all required sections are present; the map describes what exists in the source, not what should be built in the target",
    ],
  },
  "stage.extraction.target-architecture": {
    taskInstructions: "Describe the clean target architecture before implementation begins.\nExtraction guardrails:\nIf the target repository already exists, use my-dev-kit to inspect it separately from the source repository:\nIf the target repository does not exist yet, define the planned structure and contracts before any scaffolding begins.\nRequired sections:",
    validationRequirements: [
      "Do not mix source and target retrieval results.",
      "Do not carry source implementation details forward without an explicit porting decision.",
      "Do not include any architecture items from the DoNotPortList.",
      "do not start implementing in this stage.",
      "The proposal must be sufficient for implementation to begin without consulting the source repository again.",
      "Every item must map back to the SourceToTargetPortingMap or be a new target-side concern.",
      "Target repo path",
      "Target project purpose",
      "Target workflow",
      "Frontend components",
      "Backend services",
      "API routes",
      "Shared contracts",
      "State ownership",
      "Persistence policy",
      "External dependencies",
      "Testing strategy overview",
      "Source components reused",
      "Source components rewritten",
      "Source components discarded",
      "Architecture guardrails",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not include items from DoNotPortList",
      "do not reference source implementation without a porting decision",
    ],
  },
  "stage.extraction.test-implementation": {
    taskInstructions: "Prioritize non-negotiable regression tests from the GoldenBehaviorContract.\nFollow the TestStrategyPacket. Do not invent a separate test strategy.\nExtraction guardrails:\nThe TestImplementationReport must include:",
    validationRequirements: [
      "Add or update tests in the target repository only.",
      "Do not add tests to the source repository.",
      "Regression tests must cover every non-negotiable item in the GoldenBehaviorContract.",
      "Do not claim tests passed unless command evidence is included.",
      "test files changed (target repository only)",
      "tests added",
      "tests updated",
      "GoldenBehaviorContract items covered",
      "behaviors covered",
      "invariants covered",
      "state transitions covered",
      "derived values covered",
      "boundaries covered",
      "external contracts covered",
      "failure modes covered",
      "TestStrategyPacket items not implemented",
      "reason for each missing test",
      "verification commands to run",
    ],
    stopConditions: [
      "do not replace the TestStrategyPacket with a new unrelated strategy",
      "do not change production behavior unless reporting a blocker",
      "do not add tests to the source repository",
    ],
  },
  "stage.extraction.test-strategy": {
    taskInstructions: "Derive test responsibilities from the GoldenBehaviorContract, BehaviorModel, and PseudocodePacket.\nDo not write test files in this stage.\nExtraction guardrails:\nThe TestStrategyPacket must include:\nEach test responsibility must trace to at least one of:\nEach test responsibility must additionally record a stable ID and explicit criticality: \"test responsibility ID:\", \"criticality: critical | noncritical\", \"traces to:\", \"setup:\", \"action or trigger:\", \"expected result:\", \"test level:\". No responsibility ID may repeat. Criticality is owned by this packet, not by any external retrieval tool.",
    validationRequirements: [
      "test responsibility ID (stable, no duplicates)",
      "criticality: critical or noncritical (orchestrator-owned; do not infer from wording)",
      "traces to",
      "setup",
      "action or trigger",
      "expected result",
      "test level",
      "Do not test source repository behavior.",
      "Do not write test files in this stage.",
      "Do not start implementing code.",
      "contract tests (from GoldenBehaviorContract)",
      "backend unit tests",
      "frontend component tests",
      "state behavior tests",
      "integration tests",
      "E2E tests for the full extracted workflow",
      "regression tests for every non-negotiable item in the GoldenBehaviorContract",
      "behavior under test",
      "participating layers",
      "state variables",
      "events",
      "derived values",
      "invariants",
      "boundaries and partitions",
      "external contracts",
      "relevant failure modes",
      "test matrix",
      "test level assignment (unit / component / integration / end-to-end)",
      "required verification commands",
      "coverage gaps",
      "golden behavior contract item",
      "behavior",
      "invariant",
      "state transition",
      "derived value",
      "boundary",
      "external contract",
      "failure mode",
    ],
    stopConditions: [
      "do not write test files in this stage",
      "do not write production code",
      "do not invent behavior not in GoldenBehaviorContract or BehaviorModel",
    ],
  },
  "stage.extraction.verification": {
    taskInstructions: "Do not validate the source repository unless explicitly requested by the request brief.\nExtraction guardrails:\nThe VerificationReport must include:",
    validationRequirements: [
      "Run all validation commands from inside the target repository.",
      "Do not claim checks passed unless actual command output was produced.",
      "Do not hide failed commands.",
      "commands run",
      "working directory for each command (should be the target repository)",
      "exit codes",
      "pass/fail status",
      "output summary",
      "failed tests if any",
      "GoldenBehaviorContract items verified by tests",
      "skipped checks",
      "reason for skipped checks",
      "environment notes if relevant",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless command output was produced",
      "do not hide failed commands",
      "do not validate source repository unless explicitly requested",
    ],
  },
  "stage.feature.architecture-context": {
    taskInstructions: "Retrieve bounded project context and synthesize it into the required workflow artifact.\n1. Supporting retrieval report\n2. Required workflow artifact\nLater workflow stages consume ArchitectureContextPacket.\nDo not dump raw retrieval output directly into ArchitectureContextPacket.\nSynthesize retrieval evidence into the artifact before writing it.\nGraph-guided context acquisition sequence (when my-dev-kit is available):\nStep 1 - Index or refresh the target repository:\nnpx @dailephd/my-dev-kit index --root . --src src --out .my-dev-kit --call-graph --json\nStep 2 - Search for task-specific candidate nodes:\nnpx @dailephd/my-dev-kit search --index .my-dev-kit --query \"<task-specific term>\" --limit 20 --json\nRun multiple queries for different aspects of the request.\nStep 3 - Look up selected nodes and their relationships:\nnpx @dailephd/my-dev-kit lookup --index .my-dev-kit --node \"<selected-node-id>\" --depth 1 --json\nStep 4 - Slice around the strongest relevant node:\nnpx @dailephd/my-dev-kit slice --index .my-dev-kit --node \"<strongest-node-id>\" --depth 2 --direction both --out .my-dev-kit/<task-name>-slice.json --json\nStep 5 - Retrieve exact symbol source (preferred):\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --node \"<symbol-node-id>\" --max-lines 160 --format numbered\nor:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --symbol \"<symbol-name>\" --max-lines 160 --format numbered\nStep 6 - Use line-range retrieval only as fallback when symbol retrieval is insufficient:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --start <start-line> --end <end-line> --max-lines <cap> --format numbered\nStep 7 - Inspect semantic artifacts, tests, docs, or data-model artifacts only when relevant to the task.\nStep 8 - Avoid whole-file reading unless bounded retrieval is insufficient. If a whole file must be read, state why.\nIf my-dev-kit is unavailable, use focused manual inspection of relevant files and symbols. Document what was inspected, why, and what bounded context was gathered.\nThe ArchitectureContextPacket must identify:",
    validationRequirements: [
      "relevant files",
      "relevant symbols",
      "relevant components, modules, routes, commands, services, or data boundaries",
      "relevant tests",
      "relevant docs",
      "state owners and data owners",
      "upstream dependencies",
      "downstream consumers",
      "existing patterns to preserve",
      "likely files or modules involved in this change",
      "context gaps or uncertainty",
      "selection rationale for each major file or symbol chosen",
    ],
    stopConditions: [
      "do not redesign the feature",
      "do not write pseudocode",
      "do not implement code",
      "do not write test files",
      "do not claim implementation or test implementation work in this stage",
    ],
  },
  "stage.feature.behavior-model": {
    taskInstructions: "Define intended behavior before pseudocode, implementation, or test writing begins.\nThe BehaviorModel must define:\nTrace IDs (optional):\nAssign trace IDs to behaviors, invariants, and transitions to enable downstream traceability.\nFormat: BEH-001: description, INV-001: description, TRN-001: description.\nIf trace IDs are used, link related items using: FROM_ID -> TO_ID.\nUse canonical format (PREFIX-NNN with 3+ digits). Run: my-dev-kit-orchestrator check --trace",
    validationRequirements: [
      "behavior summary",
      "externally visible behavior",
      "internal supporting behavior",
      "state variables",
      "inputs",
      "events",
      "derived values",
      "invariants",
      "valid states",
      "invalid states",
      "boundaries and partitions",
      "empty states",
      "error states",
      "loading or pending states when relevant",
      "external contracts",
      "state transitions",
      "behavior to preserve",
      "behavior intentionally changed",
      "unresolved design questions",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not produce implementation-specific code",
    ],
  },
  "stage.feature.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "original request",
      "workflow mode",
      "run ID",
      "stages completed",
      "behavior designed",
      "architecture context used",
      "pseudocode summary",
      "tests designed",
      "implementation summary",
      "tests added or updated",
      "verification summary",
      "judge verdict",
      "unresolved risks",
      "follow-up recommendations if needed",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not hide unresolved risks",
    ],
  },
  "stage.feature.judge": {
    taskInstructions: "The JudgeReport must assess:\nand malformed IDs by running: my-dev-kit-orchestrator check --trace\nInclude trace check results or note that trace IDs were not used in this run.\nVerdict must be one of:\nPASS | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | NEED_CONTEXT | SCOPE_VIOLATION |\nNEED_VERIFICATION | BLOCKED",
    validationRequirements: [
      "implementation vs PseudocodePacket",
      "tests vs TestStrategyPacket",
      "behavior coverage",
      "architecture alignment",
      "scope control",
      "verification evidence",
      "risks and gaps",
      "trace link integrity (if trace IDs were used): check for orphan IDs, missing link targets,",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide uncertainty or gaps",
      "do not skip trace check if trace IDs are present in prior artifacts",
    ],
  },
  "stage.feature.pseudocode-packet": {
    taskInstructions: "Convert the BehaviorModel into implementation-neutral pseudocode.\nThis is the shared design contract for both implementation and testing.\nThe PseudocodePacket must define:\nTrace IDs (optional):\nAssign PSE-NNN trace IDs to pseudocode entries to enable downstream traceability.\nFormat: PSE-001: pseudocode entry. Link to behavior IDs using: BEH-001 -> PSE-001.\nUse canonical format (PREFIX-NNN with 3+ digits). Run: my-dev-kit-orchestrator check --trace",
    validationRequirements: [
      "behavior references",
      "data flow",
      "state flow",
      "state transitions",
      "derived-value rules",
      "validation rules",
      "empty-state handling",
      "error-state handling",
      "external contract handling",
      "component, module, service, route, command, or helper contracts",
      "acceptance criteria",
      "likely files or modules to modify",
      "implementation constraints",
      "assumptions preserved",
      "assumptions removed or guarded",
      "unresolved implementation questions",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not modify files",
    ],
  },
  "stage.feature.request-brief": {
    taskInstructions: "The RequestBrief must define:",
    validationRequirements: [
      "original request (verbatim from 00-request.txt)",
      "requested change",
      "target area (project, component, workflow, or command) if identifiable",
      "user-visible or externally observable behavior",
      "constraints",
      "non-goals",
      "success criteria",
      "ambiguity or missing information",
      "expected next stage: architecture-context",
    ],
    stopConditions: [
      "do not inspect code deeply in this stage",
      "do not write pseudocode",
      "do not write tests",
      "do not implement code",
    ],
  },
  "stage.feature.test-implementation": {
    taskInstructions: "Follow the TestStrategyPacket. Do not invent a separate test strategy.\nThe TestImplementationReport must include:",
    validationRequirements: [
      "test files changed",
      "tests added",
      "tests updated",
      "behaviors covered",
      "invariants covered",
      "state transitions covered",
      "derived values covered",
      "boundaries covered",
      "external contracts covered",
      "failure modes covered",
      "TestStrategyPacket items not implemented",
      "reason for each missing test",
      "verification commands to run",
    ],
    stopConditions: [
      "do not replace the TestStrategyPacket with a new unrelated strategy",
      "do not change production behavior unless reporting a blocker",
      "do not claim tests passed unless command evidence is included",
    ],
  },
  "stage.feature.test-strategy": {
    taskInstructions: "Derive test responsibilities from the BehaviorModel and PseudocodePacket.\nDo not write test files in this stage.\nThe TestStrategyPacket must identify:\nEach test responsibility must trace to at least one of:\nTrace IDs (optional):\nAssign TST-NNN trace IDs to test responsibilities to enable downstream traceability.\nFormat: TST-001: test responsibility. Link to behaviors or pseudocode: PSE-001 -> TST-001.\nUse canonical format (PREFIX-NNN with 3+ digits). Run: my-dev-kit-orchestrator check --trace\nEach test responsibility must additionally record a stable ID and explicit criticality: \"test responsibility ID:\", \"criticality: critical | noncritical\", \"traces to:\", \"setup:\", \"action or trigger:\", \"expected result:\", \"test level:\". No responsibility ID may repeat. Criticality is owned by this packet, not by any external retrieval tool.",
    validationRequirements: [
      "test responsibility ID (stable, no duplicates)",
      "criticality: critical or noncritical (orchestrator-owned; do not infer from wording)",
      "traces to",
      "setup",
      "action or trigger",
      "expected result",
      "test level",
      "behavior under test",
      "participating layers",
      "state variables",
      "events",
      "derived values",
      "invariants",
      "boundaries and partitions",
      "external contracts",
      "state transitions when relevant",
      "relevant failure modes",
      "existing tests",
      "test matrix",
      "test level assignment (unit / component / integration / end-to-end)",
      "required verification commands",
      "coverage gaps",
      "risks not covered and why",
      "behavior",
      "invariant",
      "state transition",
      "derived value",
      "boundary",
      "external contract",
      "failure mode",
    ],
    stopConditions: [
      "do not write test files in this stage",
      "do not write production code",
      "do not invent behavior not supported by prior artifacts",
      "do not include test responsibilities that cannot be traced to behavior, invariant, transition, derived value, boundary, contract, or failure mode",
    ],
  },
  "stage.feature.verification": {
    taskInstructions: "Use the commands identified in the TestStrategyPacket, ImplementationReport, and TestImplementationReport.\nRun the narrowest relevant checks first, then broader validation.\nThe VerificationReport must include:",
    validationRequirements: [
      "commands run",
      "working directory for each command",
      "exit codes",
      "pass/fail status",
      "output summary",
      "failed tests if any",
      "skipped checks",
      "reason for skipped checks",
      "environment notes if relevant",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless command output was produced",
      "do not hide failed commands",
      "do not omit skipped required checks",
    ],
  },
  "stage.greenfield.bootstrap-bundle": {
    taskInstructions: "Build the GreenfieldBootstrapBundle for the resolved starter profile. The bundle must record: the normalized brief, the selected starter profile, the starter profile summary, the stack decision, the template target categories, the documentation-generation instructions, the scaffold-planning inputs, the validation rules, the unresolved decisions, and the full-stack capability selection.",
    validationRequirements: [
      "The GreenfieldBootstrapBundleArtifact must record the resolved bundle for the selected starter profile, including the normalized brief, selected profile, starter profile summary, stack decision, template target categories, doc-generation instructions, scaffold-planning inputs, validation rules, unresolved decisions, and full-stack capability selection.",
    ],
    stopConditions: [
      "do not implement scaffold",
      "do not write project files",
      "do not claim release or security readiness",
    ],
  },
  "stage.greenfield.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "original project idea",
      "run ID",
      "stages completed",
      "product boundary summary",
      "stack decision and starter profile",
      "bootstrap bundle and project docs summary",
      "scaffold plan and implementation summary",
      "first vertical slice summary",
      "verification summary",
      "initial-index handoff summary",
      "judge verdict",
      "unresolved risks",
      "follow-up recommendations if needed",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not claim release, security, or publish completion",
    ],
  },
  "stage.greenfield.first-vertical-slice": {
    taskInstructions: "Keep the slice minimal. Do not expand into the full product.",
    validationRequirements: [
      "The FirstVerticalSlice artifact must record the one minimal runnable behavior implemented and how it ties to the product boundary.",
    ],
    stopConditions: [
      "do not expand into full product scope",
      "do not claim tests passed without verification evidence",
      "do not add unrelated features",
    ],
  },
  "stage.greenfield.idea-brief": {
    taskInstructions: "The IdeaBrief preserves the normalized project-brief information.\nThe IdeaBrief must preserve:",
    validationRequirements: [
      "raw idea text",
      "project name if provided",
      "product goal, users/audience, core workflow if provided",
      "constraints",
      "non-goals",
      "preferred stack if provided",
      "preferred profile if provided",
      "platform target if provided",
      "documentation preferences",
      "testing expectations",
      "unresolved questions",
    ],
    stopConditions: [
      "do not scaffold files",
      "do not implement code",
      "do not silently choose a mobile/Android profile as a default when the request is ambiguous about product type or mobile platform; preserve the ambiguity explicitly instead",
      "do not claim validation or release readiness",
    ],
  },
  "stage.greenfield.initial-index": {
    taskInstructions: "Use package execution; do not assume a global my-dev-kit command exists. Prefer:\nnpx @dailephd/my-dev-kit@latest index --root . --src src --out .my-dev-kit --json\nRecord whether indexing was actually run (with command, working directory, exit code, and output summary) or only planned, and why.",
    validationRequirements: [
      "The InitialIndexReport must record whether my-dev-kit indexing was actually run or only planned, including command, working directory, exit code, and output summary when run.",
    ],
    stopConditions: [
      "do not assume a global my-dev-kit command exists",
      "do not claim indexing succeeded unless command evidence exists",
      "do not run security validation",
      "do not publish",
    ],
  },
  "stage.greenfield.judge": {
    taskInstructions: "The JudgeReport must assess:\nVerdict must be one of:\nPASS | NEED_CONTEXT | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | SCOPE_VIOLATION | NEED_VERIFICATION | BLOCKED",
    validationRequirements: [
      "idea brief vs product boundary alignment",
      "stack decision and starter profile justification",
      "bootstrap bundle and project docs completeness",
      "scaffold plan followed by scaffold implementation",
      "first vertical slice tied to product boundary",
      "verification evidence",
      "initial-index handoff evidence",
      "risks and gaps",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide uncertainty",
    ],
  },
  "stage.greenfield.product-boundary": {
    taskInstructions: "The ProductBoundary must define:",
    validationRequirements: [
      "intended users",
      "core workflow",
      "constraints",
      "non-goals",
      "success criteria",
    ],
    stopConditions: [
      "do not write implementation code",
      "do not write scaffold files",
      "do not invent unsupported product scope",
    ],
  },
  "stage.greenfield.project-docs": {
    taskInstructions: "Preserve component docs as empty/unresolved unless the brief carries module hints. Validate generated content for unsupported claims before finishing.",
    validationRequirements: [
      "The project-docs report must record which documentation was generated and which sections were left explicitly unresolved.",
    ],
    stopConditions: [
      "do not update the current repository's README.md or docs/ROADMAP.md",
      "do not claim Android/mobile support in generated documentation unless the selected starter profile ID is android-compose",
      "do not claim release, security, or publish completion",
    ],
  },
  "stage.greenfield.scaffold-implementation": {
    taskInstructions: "The ScaffoldImplementationReport must include:",
    validationRequirements: [
      "files changed",
      "commands run, if any",
      "deviations from the scaffold plan",
      "blockers",
      "risks",
    ],
    stopConditions: [
      "do not claim verification success without command evidence",
      "do not broaden scope beyond scaffold-plan.txt",
      "do not add behavior for a profile other than the one selected in the bootstrap bundle",
    ],
  },
  "stage.greenfield.scaffold-plan": {
    taskInstructions: "The ScaffoldPlan must define:\nUse the bootstrap bundle's scaffoldPlanningInputs (src/greenfield/bootstrap/bootstrapBundleTypes.ts) as the source of truth; do not invent structure beyond it.",
    validationRequirements: [
      "planned file groups (illustrative paths only; this stage does not create files)",
      "first runnable behavior",
      "setup commands",
      "validation commands",
      "test expectations",
      "documentation expectations",
      "unresolved decisions",
      "non-goals",
    ],
    stopConditions: [
      "do not write scaffold files",
      "do not install dependencies",
      "do not run project creation commands",
      "do not implement first vertical slice in this stage",
      "do not add file trees for a profile other than the one selected in the bootstrap bundle",
    ],
  },
  "stage.greenfield.stack-decision": {
    taskInstructions: "Preserve unresolved stack decisions rather than inventing a choice. Do not silently default to a mobile/Android stack when the request is ambiguous; only choose it when explicitly requested.",
    validationRequirements: [
      "The StackDecision artifact must record the chosen platform-neutral stack, or explicitly record it as unresolved when the request is ambiguous.",
    ],
    stopConditions: [
      "do not implement dependencies",
      "do not install packages",
      "do not generate project files",
    ],
  },
  "stage.greenfield.starter-profile": {
    taskInstructions: "Select only from the supported starter profile IDs listed below (including recognized aliases). If the request is ambiguous or unsupported, record that result clearly; do not substitute a default silently.",
    validationRequirements: [
      "The StarterProfile artifact must record a profile ID from the canonical SUPPORTED_PROFILES registry, or explicitly record an unresolved/unsupported profile result.",
    ],
    stopConditions: [
      "do not silently substitute a mobile/Android profile for an ambiguous or unsupported request",
      "do not scaffold files",
    ],
  },
  "stage.greenfield.verification": {
    taskInstructions: "The VerificationReport must include:",
    validationRequirements: [
      "commands run",
      "working directory for each command",
      "exit codes",
      "pass/fail status",
      "output summary",
      "skipped checks and reasons",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless they actually ran",
      "do not hide failed commands",
      "do not run release, security, or publish workflow",
    ],
  },
  "stage.harden.architecture-context": {
    taskInstructions: "Retrieve bounded project context and synthesize it into the required workflow artifact.\n1. Supporting retrieval report\n2. Required workflow artifact\nLater workflow stages consume ArchitectureContextPacket.\nDo not dump raw retrieval output directly into ArchitectureContextPacket.\nSynthesize retrieval evidence into the artifact before writing it.\nGraph-guided context acquisition sequence (when my-dev-kit is available):\nStep 1 - Index or refresh the target repository:\nnpx @dailephd/my-dev-kit index --root . --src src --out .my-dev-kit --call-graph --json\nStep 2 - Search for task-specific candidate nodes:\nnpx @dailephd/my-dev-kit search --index .my-dev-kit --query \"<task-specific term>\" --limit 20 --json\nRun multiple queries for different aspects of the request.\nStep 3 - Look up selected nodes and their relationships:\nnpx @dailephd/my-dev-kit lookup --index .my-dev-kit --node \"<selected-node-id>\" --depth 1 --json\nStep 4 - Slice around the strongest relevant node:\nnpx @dailephd/my-dev-kit slice --index .my-dev-kit --node \"<strongest-node-id>\" --depth 2 --direction both --out .my-dev-kit/<task-name>-slice.json --json\nStep 5 - Retrieve exact symbol source (preferred):\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --node \"<symbol-node-id>\" --max-lines 160 --format numbered\nor:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --symbol \"<symbol-name>\" --max-lines 160 --format numbered\nStep 6 - Use line-range retrieval only as fallback when symbol retrieval is insufficient:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --start <start-line> --end <end-line> --max-lines <cap> --format numbered\nStep 7 - Inspect semantic artifacts, tests, docs, or data-model artifacts only when relevant to the task.\nStep 8 - Avoid whole-file reading unless bounded retrieval is insufficient. If a whole file must be read, state why.\nIf my-dev-kit is unavailable, use focused manual inspection of relevant files and symbols. Document what was inspected, why, and what bounded context was gathered.\nThe ArchitectureContextPacket must identify:",
    validationRequirements: [
      "relevant files",
      "relevant symbols",
      "relevant components, modules, routes, commands, services, or data boundaries",
      "relevant tests",
      "relevant docs",
      "state owners and data owners",
      "upstream dependencies",
      "downstream consumers",
      "existing patterns to preserve",
      "likely files or modules involved in this change",
      "context gaps or uncertainty",
      "selection rationale for each major file or symbol chosen",
    ],
    stopConditions: [
      "do not redesign the feature",
      "do not write pseudocode",
      "do not implement code",
      "do not write test files",
      "do not claim implementation or test implementation work in this stage",
    ],
  },
  "stage.harden.assumption-report": {
    taskInstructions: "Identify assumptions currently made by the code or design.\nFor each assumption include:",
    validationRequirements: [
      "assumption statement",
      "source of assumption",
      "where it is used",
      "what breaks if false",
      "decision (preserve / remove / validate / guard)",
      "required follow-up",
    ],
    stopConditions: [
      "do not implement code",
      "do not write tests",
    ],
  },
  "stage.harden.failure-mode-matrix": {
    taskInstructions: "Classify realistic ways the behavior can fail and decide how each should be handled.\nFor each failure mode include:",
    validationRequirements: [
      "failure mode",
      "category (input / state / contract / parser / storage / async / rendering / data volume / configuration / environment)",
      "trigger",
      "affected layer",
      "current behavior",
      "desired behavior",
      "handling strategy (prevent / recover / surface to user / log / retry / ignore safely / fail fast)",
      "required code change",
      "required test",
      "priority",
    ],
    stopConditions: [
      "do not implement code",
      "do not write tests yet",
    ],
  },
  "stage.harden.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "original request",
      "workflow mode",
      "run ID",
      "stages completed",
      "behavior designed",
      "architecture context used",
      "pseudocode summary",
      "tests designed",
      "implementation summary",
      "tests added or updated",
      "verification summary",
      "judge verdict",
      "unresolved risks",
      "follow-up recommendations if needed",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not hide unresolved risks",
    ],
  },
  "stage.harden.guard-pseudocode-packet": {
    taskInstructions: "Define pseudocode for validation, guards, recovery paths, and error or empty states.\nThe GuardPseudocodePacket must include:",
    validationRequirements: [
      "assumptions being guarded",
      "failure modes handled",
      "validation rules",
      "guard rules",
      "recovery behavior",
      "error-state behavior",
      "acceptance criteria",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not modify files",
    ],
  },
  "stage.harden.hardening-brief": {
    taskInstructions: "Define the robustness or failure-handling improvement requested.\nThe HardeningBrief must include:",
    validationRequirements: [
      "hardening goal",
      "target behavior or boundary",
      "current risk",
      "constraints",
      "success criteria",
    ],
    stopConditions: [
      "do not inspect code deeply",
      "do not write pseudocode",
      "do not implement code",
      "do not write tests",
    ],
  },
  "stage.harden.implementation": {
    taskInstructions: "Read required source files and implement from the PseudocodePacket.\nFollow the architecture and patterns identified in the ArchitectureContextPacket.\nPreserve the BehaviorModel.\nThe ImplementationReport must include:",
    validationRequirements: [
      "files read",
      "files changed",
      "behavior implemented",
      "pseudocode sections implemented",
      "assumptions preserved",
      "assumptions removed or guarded",
      "deviations from the PseudocodePacket",
      "reason for each deviation",
      "blockers encountered",
      "unresolved risks",
      "tests that should be run",
      "notes for the test implementation stage",
    ],
    stopConditions: [
      "do not broaden scope without reporting a blocker",
      "do not create parallel architecture",
      "do not claim verification success without command evidence",
      "do not ignore contradictions in prior artifacts",
      "do not modify files outside justified scope",
    ],
  },
  "stage.harden.judge": {
    taskInstructions: "The JudgeReport must assess:\nand malformed IDs by running: my-dev-kit-orchestrator check --trace\nInclude trace check results or note that trace IDs were not used in this run.\nVerdict must be one of:\nPASS | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | NEED_CONTEXT | SCOPE_VIOLATION |\nNEED_VERIFICATION | BLOCKED",
    validationRequirements: [
      "implementation vs PseudocodePacket",
      "tests vs TestStrategyPacket",
      "behavior coverage",
      "architecture alignment",
      "scope control",
      "verification evidence",
      "risks and gaps",
      "trace link integrity (if trace IDs were used): check for orphan IDs, missing link targets,",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide uncertainty or gaps",
      "do not skip trace check if trace IDs are present in prior artifacts",
    ],
  },
  "stage.harden.resilience-test-strategy": {
    taskInstructions: "Define tests that verify hardening behavior.\nThe ResilienceTestStrategy must include:\nEach test responsibility must trace to assumption, failure mode, boundary, contract, or behavior.\nDo not write test files in this stage.\nEach test responsibility must additionally record a stable ID and explicit criticality: \"test responsibility ID:\", \"criticality: critical | noncritical\", \"traces to:\", \"setup:\", \"action or trigger:\", \"expected result:\", \"test level:\". No responsibility ID may repeat. Criticality is owned by this packet, not by any external retrieval tool.",
    validationRequirements: [
      "test responsibility ID (stable, no duplicates)",
      "criticality: critical or noncritical (orchestrator-owned; do not infer from wording)",
      "traces to",
      "setup",
      "action or trigger",
      "expected result",
      "test level",
      "assumptions tested",
      "failure modes tested",
      "validation tests",
      "guard tests",
      "recovery tests",
      "error-state tests",
      "verification commands",
      "remaining risks",
    ],
    stopConditions: [
      "do not write test files in this stage",
      "do not implement code",
    ],
  },
  "stage.harden.test-implementation": {
    taskInstructions: "Follow the TestStrategyPacket. Do not invent a separate test strategy.\nThe TestImplementationReport must include:",
    validationRequirements: [
      "test files changed",
      "tests added",
      "tests updated",
      "behaviors covered",
      "invariants covered",
      "state transitions covered",
      "derived values covered",
      "boundaries covered",
      "external contracts covered",
      "failure modes covered",
      "TestStrategyPacket items not implemented",
      "reason for each missing test",
      "verification commands to run",
    ],
    stopConditions: [
      "do not replace the TestStrategyPacket with a new unrelated strategy",
      "do not change production behavior unless reporting a blocker",
      "do not claim tests passed unless command evidence is included",
    ],
  },
  "stage.harden.verification": {
    taskInstructions: "Use the commands identified in the TestStrategyPacket, ImplementationReport, and TestImplementationReport.\nRun the narrowest relevant checks first, then broader validation.\nThe VerificationReport must include:",
    validationRequirements: [
      "commands run",
      "working directory for each command",
      "exit codes",
      "pass/fail status",
      "output summary",
      "failed tests if any",
      "skipped checks",
      "reason for skipped checks",
      "environment notes if relevant",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless command output was produced",
      "do not hide failed commands",
      "do not omit skipped required checks",
    ],
  },
  "stage.refactor.architecture-context": {
    taskInstructions: "Retrieve bounded project context and synthesize it into the required workflow artifact.\n1. Supporting retrieval report\n2. Required workflow artifact\nLater workflow stages consume ArchitectureContextPacket.\nDo not dump raw retrieval output directly into ArchitectureContextPacket.\nSynthesize retrieval evidence into the artifact before writing it.\nGraph-guided context acquisition sequence (when my-dev-kit is available):\nStep 1 - Index or refresh the target repository:\nnpx @dailephd/my-dev-kit index --root . --src src --out .my-dev-kit --call-graph --json\nStep 2 - Search for task-specific candidate nodes:\nnpx @dailephd/my-dev-kit search --index .my-dev-kit --query \"<task-specific term>\" --limit 20 --json\nRun multiple queries for different aspects of the request.\nStep 3 - Look up selected nodes and their relationships:\nnpx @dailephd/my-dev-kit lookup --index .my-dev-kit --node \"<selected-node-id>\" --depth 1 --json\nStep 4 - Slice around the strongest relevant node:\nnpx @dailephd/my-dev-kit slice --index .my-dev-kit --node \"<strongest-node-id>\" --depth 2 --direction both --out .my-dev-kit/<task-name>-slice.json --json\nStep 5 - Retrieve exact symbol source (preferred):\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --node \"<symbol-node-id>\" --max-lines 160 --format numbered\nor:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --symbol \"<symbol-name>\" --max-lines 160 --format numbered\nStep 6 - Use line-range retrieval only as fallback when symbol retrieval is insufficient:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --start <start-line> --end <end-line> --max-lines <cap> --format numbered\nStep 7 - Inspect semantic artifacts, tests, docs, or data-model artifacts only when relevant to the task.\nStep 8 - Avoid whole-file reading unless bounded retrieval is insufficient. If a whole file must be read, state why.\nIf my-dev-kit is unavailable, use focused manual inspection of relevant files and symbols. Document what was inspected, why, and what bounded context was gathered.\nThe ArchitectureContextPacket must identify:",
    validationRequirements: [
      "relevant files",
      "relevant symbols",
      "relevant components, modules, routes, commands, services, or data boundaries",
      "relevant tests",
      "relevant docs",
      "state owners and data owners",
      "upstream dependencies",
      "downstream consumers",
      "existing patterns to preserve",
      "likely files or modules involved in this change",
      "context gaps or uncertainty",
      "selection rationale for each major file or symbol chosen",
    ],
    stopConditions: [
      "do not redesign the feature",
      "do not write pseudocode",
      "do not implement code",
      "do not write test files",
      "do not claim implementation or test implementation work in this stage",
    ],
  },
  "stage.refactor.compatibility-test-strategy": {
    taskInstructions: "Define tests that prove the refactor preserved behavior.\nThe CompatibilityTestStrategy must include:\nEach test responsibility must trace to behavior, invariant, transition, derived value, boundary, contract, or failure mode.\nDo not write test files in this stage.\nEach test responsibility must additionally record a stable ID and explicit criticality: \"test responsibility ID:\", \"criticality: critical | noncritical\", \"traces to:\", \"setup:\", \"action or trigger:\", \"expected result:\", \"test level:\". No responsibility ID may repeat. Criticality is owned by this packet, not by any external retrieval tool.",
    validationRequirements: [
      "test responsibility ID (stable, no duplicates)",
      "criticality: critical or noncritical (orchestrator-owned; do not infer from wording)",
      "traces to",
      "setup",
      "action or trigger",
      "expected result",
      "test level",
      "preserved behavior",
      "compatibility test responsibilities",
      "existing tests to run",
      "new tests needed",
      "verification commands",
    ],
    stopConditions: [
      "do not write test files in this stage",
      "do not implement code",
    ],
  },
  "stage.refactor.existing-behavior-map": {
    taskInstructions: "Map the behavior that must remain stable during the refactor.\nThe ExistingBehaviorMap must include:",
    validationRequirements: [
      "current behaviors",
      "state variables",
      "events",
      "derived values",
      "invariants",
      "external contracts",
      "existing tests",
      "behavior gaps",
    ],
    stopConditions: [
      "do not implement code",
      "do not write tests",
      "do not write pseudocode",
    ],
  },
  "stage.refactor.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "original request",
      "workflow mode",
      "run ID",
      "stages completed",
      "behavior designed",
      "architecture context used",
      "pseudocode summary",
      "tests designed",
      "implementation summary",
      "tests added or updated",
      "verification summary",
      "judge verdict",
      "unresolved risks",
      "follow-up recommendations if needed",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not hide unresolved risks",
    ],
  },
  "stage.refactor.implementation": {
    taskInstructions: "Read required source files and implement from the PseudocodePacket.\nFollow the architecture and patterns identified in the ArchitectureContextPacket.\nPreserve the BehaviorModel.\nThe ImplementationReport must include:",
    validationRequirements: [
      "files read",
      "files changed",
      "behavior implemented",
      "pseudocode sections implemented",
      "assumptions preserved",
      "assumptions removed or guarded",
      "deviations from the PseudocodePacket",
      "reason for each deviation",
      "blockers encountered",
      "unresolved risks",
      "tests that should be run",
      "notes for the test implementation stage",
    ],
    stopConditions: [
      "do not broaden scope without reporting a blocker",
      "do not create parallel architecture",
      "do not claim verification success without command evidence",
      "do not ignore contradictions in prior artifacts",
      "do not modify files outside justified scope",
    ],
  },
  "stage.refactor.judge": {
    taskInstructions: "The JudgeReport must assess:\nand malformed IDs by running: my-dev-kit-orchestrator check --trace\nInclude trace check results or note that trace IDs were not used in this run.\nVerdict must be one of:\nPASS | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | NEED_CONTEXT | SCOPE_VIOLATION |\nNEED_VERIFICATION | BLOCKED",
    validationRequirements: [
      "implementation vs PseudocodePacket",
      "tests vs TestStrategyPacket",
      "behavior coverage",
      "architecture alignment",
      "scope control",
      "verification evidence",
      "risks and gaps",
      "trace link integrity (if trace IDs were used): check for orphan IDs, missing link targets,",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide uncertainty or gaps",
      "do not skip trace check if trace IDs are present in prior artifacts",
    ],
  },
  "stage.refactor.preserved-invariant-list": {
    taskInstructions: "Define what must remain true after the refactor.\nThe PreservedInvariantList must include:",
    validationRequirements: [
      "invariants to preserve",
      "affected code areas",
      "tests protecting each invariant",
      "missing tests",
    ],
    stopConditions: [
      "do not implement code",
      "do not write test files yet",
    ],
  },
  "stage.refactor.refactor-brief": {
    taskInstructions: "Define the intended code-structure change and behavior-preservation requirement.\nThe RefactorBrief must include:",
    validationRequirements: [
      "refactor goal",
      "behavior that must remain unchanged",
      "target area",
      "constraints",
      "non-goals",
      "success criteria",
    ],
    stopConditions: [
      "do not inspect code deeply",
      "do not write pseudocode",
      "do not implement code",
      "do not write tests",
    ],
  },
  "stage.refactor.refactor-pseudocode-packet": {
    taskInstructions: "Define the implementation-neutral design for the refactor. Preserve the behavior identified in ExistingBehaviorMap.\nThe RefactorPseudocodePacket must include:",
    validationRequirements: [
      "target structure",
      "data flow changes",
      "invariants preserved",
      "files allowed to change",
      "component or module contracts",
      "acceptance criteria",
      "assumptions preserved",
      "unresolved implementation questions",
    ],
    stopConditions: [
      "do not write production code",
      "do not write test files",
      "do not modify files",
    ],
  },
  "stage.refactor.test-implementation": {
    taskInstructions: "Follow the TestStrategyPacket. Do not invent a separate test strategy.\nThe TestImplementationReport must include:",
    validationRequirements: [
      "test files changed",
      "tests added",
      "tests updated",
      "behaviors covered",
      "invariants covered",
      "state transitions covered",
      "derived values covered",
      "boundaries covered",
      "external contracts covered",
      "failure modes covered",
      "TestStrategyPacket items not implemented",
      "reason for each missing test",
      "verification commands to run",
    ],
    stopConditions: [
      "do not replace the TestStrategyPacket with a new unrelated strategy",
      "do not change production behavior unless reporting a blocker",
      "do not claim tests passed unless command evidence is included",
    ],
  },
  "stage.refactor.verification": {
    taskInstructions: "Use the commands identified in the TestStrategyPacket, ImplementationReport, and TestImplementationReport.\nRun the narrowest relevant checks first, then broader validation.\nThe VerificationReport must include:",
    validationRequirements: [
      "commands run",
      "working directory for each command",
      "exit codes",
      "pass/fail status",
      "output summary",
      "failed tests if any",
      "skipped checks",
      "reason for skipped checks",
      "environment notes if relevant",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless command output was produced",
      "do not hide failed commands",
      "do not omit skipped required checks",
    ],
  },
  "stage.repair.architecture-context": {
    taskInstructions: "Retrieve bounded project context and synthesize it into the required workflow artifact.\n1. Supporting retrieval report\n2. Required workflow artifact\nLater workflow stages consume ArchitectureContextPacket.\nDo not dump raw retrieval output directly into ArchitectureContextPacket.\nSynthesize retrieval evidence into the artifact before writing it.\nGraph-guided context acquisition sequence (when my-dev-kit is available):\nStep 1 - Index or refresh the target repository:\nnpx @dailephd/my-dev-kit index --root . --src src --out .my-dev-kit --call-graph --json\nStep 2 - Search for task-specific candidate nodes:\nnpx @dailephd/my-dev-kit search --index .my-dev-kit --query \"<task-specific term>\" --limit 20 --json\nRun multiple queries for different aspects of the request.\nStep 3 - Look up selected nodes and their relationships:\nnpx @dailephd/my-dev-kit lookup --index .my-dev-kit --node \"<selected-node-id>\" --depth 1 --json\nStep 4 - Slice around the strongest relevant node:\nnpx @dailephd/my-dev-kit slice --index .my-dev-kit --node \"<strongest-node-id>\" --depth 2 --direction both --out .my-dev-kit/<task-name>-slice.json --json\nStep 5 - Retrieve exact symbol source (preferred):\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --node \"<symbol-node-id>\" --max-lines 160 --format numbered\nor:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --symbol \"<symbol-name>\" --max-lines 160 --format numbered\nStep 6 - Use line-range retrieval only as fallback when symbol retrieval is insufficient:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --start <start-line> --end <end-line> --max-lines <cap> --format numbered\nStep 7 - Inspect semantic artifacts, tests, docs, or data-model artifacts only when relevant to the task.\nStep 8 - Avoid whole-file reading unless bounded retrieval is insufficient. If a whole file must be read, state why.\nIf my-dev-kit is unavailable, use focused manual inspection of relevant files and symbols. Document what was inspected, why, and what bounded context was gathered.\nThe ArchitectureContextPacket must identify:",
    validationRequirements: [
      "relevant files",
      "relevant symbols",
      "relevant components, modules, routes, commands, services, or data boundaries",
      "relevant tests",
      "relevant docs",
      "state owners and data owners",
      "upstream dependencies",
      "downstream consumers",
      "existing patterns to preserve",
      "likely files or modules involved in this change",
      "context gaps or uncertainty",
      "selection rationale for each major file or symbol chosen",
    ],
    stopConditions: [
      "do not redesign the feature",
      "do not write pseudocode",
      "do not implement code",
      "do not write test files",
      "do not claim implementation or test implementation work in this stage",
    ],
  },
  "stage.repair.behavior-trace": {
    taskInstructions: "Connect the observed behavior to the intended behavior model or pseudocode path.\nThe BehaviorTrace must identify:",
    validationRequirements: [
      "observed behavior reference",
      "matched behavior artifact if available",
      "matched behavior rule",
      "matched pseudocode section if available",
      "expected data flow",
      "expected state flow",
      "expected output",
      "missing design artifact if no match found",
    ],
    stopConditions: [
      "do not modify code",
      "do not write tests",
      "do not implement fixes yet",
    ],
  },
  "stage.repair.correction-design": {
    taskInstructions: "Define how the system should be corrected before implementation.\nThe CorrectionDesign must include:",
    validationRequirements: [
      "correction goal",
      "artifact to update if any",
      "code behavior to change",
      "tests to add or update",
      "acceptance criteria",
      "risks",
    ],
    stopConditions: [
      "do not implement code in this stage",
      "do not write test files",
    ],
  },
  "stage.repair.divergence-report": {
    taskInstructions: "Identify the first point where actual behavior diverges from intended behavior.\nThe DivergenceReport must include:",
    validationRequirements: [
      "expected path",
      "actual path",
      "first divergence point",
      "affected layer",
      "evidence",
      "correction category (behavior design update / pseudocode update / implementation correction / test correction / external contract correction / runtime state ordering correction / artifact update)",
      "uncertainty",
    ],
    stopConditions: [
      "do not modify code",
      "do not implement fixes yet",
    ],
  },
  "stage.repair.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "original request",
      "workflow mode",
      "run ID",
      "stages completed",
      "behavior designed",
      "architecture context used",
      "pseudocode summary",
      "tests designed",
      "implementation summary",
      "tests added or updated",
      "verification summary",
      "judge verdict",
      "unresolved risks",
      "follow-up recommendations if needed",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not hide unresolved risks",
    ],
  },
  "stage.repair.implementation": {
    taskInstructions: "Read required source files and implement from the PseudocodePacket.\nFollow the architecture and patterns identified in the ArchitectureContextPacket.\nPreserve the BehaviorModel.\nThe ImplementationReport must include:",
    validationRequirements: [
      "files read",
      "files changed",
      "behavior implemented",
      "pseudocode sections implemented",
      "assumptions preserved",
      "assumptions removed or guarded",
      "deviations from the PseudocodePacket",
      "reason for each deviation",
      "blockers encountered",
      "unresolved risks",
      "tests that should be run",
      "notes for the test implementation stage",
    ],
    stopConditions: [
      "do not broaden scope without reporting a blocker",
      "do not create parallel architecture",
      "do not claim verification success without command evidence",
      "do not ignore contradictions in prior artifacts",
      "do not modify files outside justified scope",
    ],
  },
  "stage.repair.judge": {
    taskInstructions: "The JudgeReport must assess:\nand malformed IDs by running: my-dev-kit-orchestrator check --trace\nInclude trace check results or note that trace IDs were not used in this run.\nVerdict must be one of:\nPASS | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | NEED_CONTEXT | SCOPE_VIOLATION |\nNEED_VERIFICATION | BLOCKED",
    validationRequirements: [
      "implementation vs PseudocodePacket",
      "tests vs TestStrategyPacket",
      "behavior coverage",
      "architecture alignment",
      "scope control",
      "verification evidence",
      "risks and gaps",
      "trace link integrity (if trace IDs were used): check for orphan IDs, missing link targets,",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide uncertainty or gaps",
      "do not skip trace check if trace IDs are present in prior artifacts",
    ],
  },
  "stage.repair.observed-behavior-report": {
    taskInstructions: "Capture the wrong or unexpected behavior without jumping to code-level causes.\nThe ObservedBehaviorReport must define:",
    validationRequirements: [
      "observed behavior (verbatim or close description)",
      "expected behavior if known",
      "triggering action or system event",
      "visible output or runtime symptom",
      "affected workflow or area",
      "frequency or reproducibility",
      "evidence available",
      "uncertainty",
    ],
    stopConditions: [
      "do not guess code-level causes yet",
      "do not write pseudocode",
      "do not write tests",
      "do not implement code",
    ],
  },
  "stage.repair.regression-test-strategy": {
    taskInstructions: "Define tests that prove the observed divergence cannot recur and cover related behavior.\nThe RegressionTestStrategy must include:\nEach test responsibility must trace to behavior, invariant, transition, derived value, boundary, contract, or failure mode.\nDo not write test files in this stage.\nEach test responsibility must additionally record a stable ID and explicit criticality: \"test responsibility ID:\", \"criticality: critical | noncritical\", \"traces to:\", \"setup:\", \"action or trigger:\", \"expected result:\", \"test level:\". No responsibility ID may repeat. Criticality is owned by this packet, not by any external retrieval tool.",
    validationRequirements: [
      "test responsibility ID (stable, no duplicates)",
      "criticality: critical or noncritical (orchestrator-owned; do not infer from wording)",
      "traces to",
      "setup",
      "action or trigger",
      "expected result",
      "test level",
      "divergence being protected against",
      "behavior or pseudocode rule being protected",
      "regression test responsibilities",
      "related boundary or transition coverage",
      "verification commands",
    ],
    stopConditions: [
      "do not write test files in this stage",
      "do not implement code",
    ],
  },
  "stage.repair.test-implementation": {
    taskInstructions: "Follow the TestStrategyPacket. Do not invent a separate test strategy.\nThe TestImplementationReport must include:",
    validationRequirements: [
      "test files changed",
      "tests added",
      "tests updated",
      "behaviors covered",
      "invariants covered",
      "state transitions covered",
      "derived values covered",
      "boundaries covered",
      "external contracts covered",
      "failure modes covered",
      "TestStrategyPacket items not implemented",
      "reason for each missing test",
      "verification commands to run",
    ],
    stopConditions: [
      "do not replace the TestStrategyPacket with a new unrelated strategy",
      "do not change production behavior unless reporting a blocker",
      "do not claim tests passed unless command evidence is included",
    ],
  },
  "stage.repair.verification": {
    taskInstructions: "Use the commands identified in the TestStrategyPacket, ImplementationReport, and TestImplementationReport.\nRun the narrowest relevant checks first, then broader validation.\nThe VerificationReport must include:",
    validationRequirements: [
      "commands run",
      "working directory for each command",
      "exit codes",
      "pass/fail status",
      "output summary",
      "failed tests if any",
      "skipped checks",
      "reason for skipped checks",
      "environment notes if relevant",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless command output was produced",
      "do not hide failed commands",
      "do not omit skipped required checks",
    ],
  },
  "stage.test.architecture-context": {
    taskInstructions: "Retrieve bounded project context and synthesize it into the required workflow artifact.\n1. Supporting retrieval report\n2. Required workflow artifact\nLater workflow stages consume ArchitectureContextPacket.\nDo not dump raw retrieval output directly into ArchitectureContextPacket.\nSynthesize retrieval evidence into the artifact before writing it.\nGraph-guided context acquisition sequence (when my-dev-kit is available):\nStep 1 - Index or refresh the target repository:\nnpx @dailephd/my-dev-kit index --root . --src src --out .my-dev-kit --call-graph --json\nStep 2 - Search for task-specific candidate nodes:\nnpx @dailephd/my-dev-kit search --index .my-dev-kit --query \"<task-specific term>\" --limit 20 --json\nRun multiple queries for different aspects of the request.\nStep 3 - Look up selected nodes and their relationships:\nnpx @dailephd/my-dev-kit lookup --index .my-dev-kit --node \"<selected-node-id>\" --depth 1 --json\nStep 4 - Slice around the strongest relevant node:\nnpx @dailephd/my-dev-kit slice --index .my-dev-kit --node \"<strongest-node-id>\" --depth 2 --direction both --out .my-dev-kit/<task-name>-slice.json --json\nStep 5 - Retrieve exact symbol source (preferred):\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --node \"<symbol-node-id>\" --max-lines 160 --format numbered\nor:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --symbol \"<symbol-name>\" --max-lines 160 --format numbered\nStep 6 - Use line-range retrieval only as fallback when symbol retrieval is insufficient:\nnpx @dailephd/my-dev-kit source --index .my-dev-kit --file \"<file-path>\" --start <start-line> --end <end-line> --max-lines <cap> --format numbered\nStep 7 - Inspect semantic artifacts, tests, docs, or data-model artifacts only when relevant to the task.\nStep 8 - Avoid whole-file reading unless bounded retrieval is insufficient. If a whole file must be read, state why.\nIf my-dev-kit is unavailable, use focused manual inspection of relevant files and symbols. Document what was inspected, why, and what bounded context was gathered.\nThe ArchitectureContextPacket must identify:",
    validationRequirements: [
      "relevant files",
      "relevant symbols",
      "relevant components, modules, routes, commands, services, or data boundaries",
      "relevant tests",
      "relevant docs",
      "state owners and data owners",
      "upstream dependencies",
      "downstream consumers",
      "existing patterns to preserve",
      "likely files or modules involved in this change",
      "context gaps or uncertainty",
      "selection rationale for each major file or symbol chosen",
    ],
    stopConditions: [
      "do not redesign the feature",
      "do not write pseudocode",
      "do not implement code",
      "do not write test files",
      "do not claim implementation or test implementation work in this stage",
    ],
  },
  "stage.test.behavior-reconstruction": {
    taskInstructions: "Reconstruct behavior for the target feature when no BehaviorModel exists yet.\nThe BehaviorReconstruction must include:",
    validationRequirements: [
      "observed existing behavior",
      "current architecture evidence",
      "state variables",
      "events",
      "derived values",
      "invariants",
      "external contracts",
      "uncertainty",
    ],
    stopConditions: [
      "do not write test files",
      "do not implement code",
    ],
  },
  "stage.test.final-report": {
    taskInstructions: "The FinalReport must include:",
    validationRequirements: [
      "original request",
      "workflow mode",
      "run ID",
      "stages completed",
      "behavior designed",
      "architecture context used",
      "pseudocode summary",
      "tests designed",
      "implementation summary",
      "tests added or updated",
      "verification summary",
      "judge verdict",
      "unresolved risks",
      "follow-up recommendations if needed",
    ],
    stopConditions: [
      "do not exaggerate success",
      "do not omit failed or skipped verification",
      "do not hide unresolved risks",
    ],
  },
  "stage.test.judge": {
    taskInstructions: "The JudgeReport must assess:\nand malformed IDs by running: my-dev-kit-orchestrator check --trace\nInclude trace check results or note that trace IDs were not used in this run.\nVerdict must be one of:\nPASS | DESIGN_INCOMPLETE | PSEUDOCODE_INCOMPLETE | IMPLEMENTATION_MISMATCH |\nTEST_COVERAGE_INCOMPLETE | ARCHITECTURE_MISMATCH | NEED_CONTEXT | SCOPE_VIOLATION |\nNEED_VERIFICATION | BLOCKED",
    validationRequirements: [
      "implementation vs PseudocodePacket",
      "tests vs TestStrategyPacket",
      "behavior coverage",
      "architecture alignment",
      "scope control",
      "verification evidence",
      "risks and gaps",
      "trace link integrity (if trace IDs were used): check for orphan IDs, missing link targets,",
    ],
    stopConditions: [
      "do not rewrite code",
      "do not approve without verification evidence",
      "do not hide uncertainty or gaps",
      "do not skip trace check if trace IDs are present in prior artifacts",
    ],
  },
  "stage.test.pseudocode-summary": {
    taskInstructions: "Summarize existing implementation behavior in pseudocode form when no full PseudocodePacket exists.\nThe PseudocodeSummary must include:",
    validationRequirements: [
      "implementation-neutral behavior summary",
      "data flow",
      "state flow",
      "derived values",
      "validation rules",
      "error or empty state handling",
      "uncertainty",
    ],
    stopConditions: [
      "do not write test files",
      "do not implement code",
    ],
  },
  "stage.test.test-implementation": {
    taskInstructions: "Follow the TestStrategyPacket. Do not invent a separate test strategy.\nThe TestImplementationReport must include:",
    validationRequirements: [
      "test files changed",
      "tests added",
      "tests updated",
      "behaviors covered",
      "invariants covered",
      "state transitions covered",
      "derived values covered",
      "boundaries covered",
      "external contracts covered",
      "failure modes covered",
      "TestStrategyPacket items not implemented",
      "reason for each missing test",
      "verification commands to run",
    ],
    stopConditions: [
      "do not replace the TestStrategyPacket with a new unrelated strategy",
      "do not change production behavior unless reporting a blocker",
      "do not claim tests passed unless command evidence is included",
    ],
  },
  "stage.test.test-strategy": {
    taskInstructions: "Derive test responsibilities from the BehaviorModel and PseudocodePacket.\nDo not write test files in this stage.\nThe TestStrategyPacket must identify:\nEach test responsibility must trace to at least one of:\nTrace IDs (optional):\nAssign TST-NNN trace IDs to test responsibilities to enable downstream traceability.\nFormat: TST-001: test responsibility. Link to behaviors or pseudocode: PSE-001 -> TST-001.\nUse canonical format (PREFIX-NNN with 3+ digits). Run: my-dev-kit-orchestrator check --trace\nEach test responsibility must additionally record a stable ID and explicit criticality: \"test responsibility ID:\", \"criticality: critical | noncritical\", \"traces to:\", \"setup:\", \"action or trigger:\", \"expected result:\", \"test level:\". No responsibility ID may repeat. Criticality is owned by this packet, not by any external retrieval tool.",
    validationRequirements: [
      "test responsibility ID (stable, no duplicates)",
      "criticality: critical or noncritical (orchestrator-owned; do not infer from wording)",
      "traces to",
      "setup",
      "action or trigger",
      "expected result",
      "test level",
      "behavior under test",
      "participating layers",
      "state variables",
      "events",
      "derived values",
      "invariants",
      "boundaries and partitions",
      "external contracts",
      "state transitions when relevant",
      "relevant failure modes",
      "existing tests",
      "test matrix",
      "test level assignment (unit / component / integration / end-to-end)",
      "required verification commands",
      "coverage gaps",
      "risks not covered and why",
      "behavior",
      "invariant",
      "state transition",
      "derived value",
      "boundary",
      "external contract",
      "failure mode",
    ],
    stopConditions: [
      "do not write test files in this stage",
      "do not write production code",
      "do not invent behavior not supported by prior artifacts",
      "do not include test responsibilities that cannot be traced to behavior, invariant, transition, derived value, boundary, contract, or failure mode",
    ],
  },
  "stage.test.test-target-brief": {
    taskInstructions: "Define the target of this test-design or test-implementation run.\nThe TestTargetBrief must include:",
    validationRequirements: [
      "test target",
      "target behavior or workflow",
      "whether code changes are allowed",
      "desired test depth",
      "constraints",
      "success criteria",
    ],
    stopConditions: [
      "do not write test files yet",
      "do not implement code",
      "do not write pseudocode",
    ],
  },
  "stage.test.verification": {
    taskInstructions: "Use the commands identified in the TestStrategyPacket, ImplementationReport, and TestImplementationReport.\nRun the narrowest relevant checks first, then broader validation.\nThe VerificationReport must include:",
    validationRequirements: [
      "commands run",
      "working directory for each command",
      "exit codes",
      "pass/fail status",
      "output summary",
      "failed tests if any",
      "skipped checks",
      "reason for skipped checks",
      "environment notes if relevant",
      "remaining verification gaps",
    ],
    stopConditions: [
      "do not claim checks passed unless command output was produced",
      "do not hide failed commands",
      "do not omit skipped required checks",
    ],
  },
};
